### ISSUE TITLE
Decode PubkeyScript causes DataIntegrityError

### ISSUE THREAD

**Issue by oacdutra** [LNP-WG/lightning_encoding#2]
Hi @dr-orlovsky, 

I tried to decode a `PubkeyScript` using `lightning_deserialize` from message **shutdown channel** by clightning, but it occurred an error:

```
Err(DataIntegrityError("parse failed: data not consumed entirely when explicitly deserializing"))
```

According to the BOLT-2 spec, we can receive one of the following `scriptpubkey`:

- `OP_0` `20` 20-bytes (version 0 pay to witness pubkey hash), OR
- `OP_0` `32` 32-bytes (version 0 pay to witness script hash), OR
if (and only if) `option_shutdown_anysegwit` is negotiated:
- `OP_1` through `OP_16` inclusive, followed by a single push of 2 to 40 bytes (witness program versions 1 through 16)

The `Script::lightning_deserialize` cannot distinguish which type of script is being passed.

You can test this by adding the bellow test in **bitcoin.rs**:

```lang=rust
#[cfg(test)]
mod test {
    use bitcoin::Script;
    use crate::LightningDecode;

    #[test]
    fn real_clightning_scriptpubkey() {
        // Real scriptpubkey sent by clightning
        let msg_recv = [
            0, 22, 0, 20, 42, 238, 172, 27, 222, 161, 61,
            181, 251, 208, 97, 79, 71, 255, 98, 8, 213, 205, 114, 94,
        ];
        let message = Script::lightning_deserialize(&msg_recv);
        println!("{:#?}", message);
        assert_eq!(true, message.is_ok());
    }
}
```

Expected Result:
```
Ok(PubkeyScript(Script(OP_DUP OP_HASH160 OP_PUSHBYTES_20 00142aeeac1bdea13db5fbd0614f47ff6208d5cd OP_EQUALVERIFY OP_CHECKSIG)))
``` 

I bypassed the issue by deserializing each type of script according to its size.

I hope this help.

Thanks

**Comment by dr-orlovsky** [comment]
So we need an ability to analyze the length of the received message?

**Comment by oacdutra** [comment]
> So we need an ability to analyze the length of the received message?

Yeah, other approach is use and/or create something similar to [`ScriptBuf`](https://github.com/rust-bitcoin/rust-bitcoin/blob/b6387db47fb8f5a99fe37a1428d04d01e4bf772c/bitcoin/src/blockdata/script/types/owned.rs#L31) in the `bp-foundation`.

The `ScriptBuf` allows manager and detect the type of scripts more easy than `Script` trait. I think will be release only version 0.30.

**Comment by dr-orlovsky** [comment]
So the error was completely unrelated to what was described in this issue. The real case of the problem was different: https://github.com/LNP-WG/lightning_encoding/pull/4#issuecomment-1464874585

**Comment by oacdutra** [comment]
The open_channel message (bolt2) has a field called shutdown_scriptpubkey; this field is optional. The lightning decode returns DataIntegrityError when this field is empty.

I'm not sure how to solve this issue, but the TLV fields need a way to check if vector bytes are empty. If true, "skip" the parsing process.
