### ISSUE TITLE
Decode TLV PubkeyScript causes DataIntegrityError

### ISSUE THREAD

**Issue by oacdutra** [LNP-WG/lightning_encoding#6]
The `open_channel` message (bolt2) has a field called `shutdown_scriptpubkey`; this field is optional. The lightning decode returns DataIntegrityError when this field is empty.

I'm not sure how to solve this issue, but the TLV fields need a way to check if vector bytes are empty. If true, "skip" the parsing process.

**Comment by dr-orlovsky** [comment]
Sorry, why you created a new duplicate of the issue https://github.com/LNP-WG/lightning_encoding/issues/2? I just solved it yesterday with https://github.com/LNP-WG/lightning_encoding/pull/4?

**Comment by dr-orlovsky** [comment]
Ok, I see your explanations in https://github.com/LNP-WG/lnp-core/pull/30#pullrequestreview-1335911092. Can you pls delete this duplicate issue and re-open #2?

**Comment by oacdutra** [comment]
Hi @dr-orlovsky, for some reason, I cannot open #2

**Comment by dr-orlovsky** [comment]
I have re-opened it
